### ISSUE TITLE
1.19.4 version tagged as 1.19.2 - causing crash

### ISSUE THREAD

**Issue by zachsai** [AzureDoom/Erroring-Entity-Remover-ReForged#2]
Please fix the tagging on curseforge so it doesnt suggest updating while on 1.19.2 to a 1.19.4 version that crashes the game

**Comment by AzureDoom** [comment]
Latest should work on 1.19.2 just fine, is it not?

**Comment by zachsai** [comment]
Nope, causes a crash.
Took 30 minutes + to find that it was the cause

**Comment by AzureDoom** [comment]
Can you please send a log so I may test? I'll get it sorted so it works properly on .2 as it should

**Comment by zachsai** [comment]
The log does not show any error referring to the mod fyi, thats why it took so long. I'll stick with the previous version in the meantime.
I'm heading off to work, thus I'm not in the possibility to send a log currently

**Comment by AzureDoom** [comment]
![2023-04-29_11 41 19](https://user-images.githubusercontent.com/7415711/235311242-39288b1f-e563-461c-9975-23c2273397ee.png)
Check you are fully up to date. Mod is working for me.

**Comment by zachsai** [comment]
Test with forge 42.2.3 if possible

**Comment by AzureDoom** [comment]
> Test with forge 42.2.3 if possible

![2023-04-30_18 49 55](https://user-images.githubusercontent.com/7415711/235379580-587287d8-191b-4477-9ad1-cb1b412e3f8b.png)
Did it with the latest (42.2.8) as well, still launching just fine.

**Comment by AzureDoom** [comment]
This was found to be the fault of mods that are using the **beta** version of MixinExtra instead of the release version. New version is pushed using the beta.
