### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by WenXin20** [AzureDoom/Erroring-Entity-Remover-ReForged#3]
```
EeReforged v1.0.4
Minecraft v1.19.2
Forge v43.2.7
```

The game immediately crashes on launch, possibly due to a conflict with the mod [Obscure Api v9](https://www.curseforge.com/minecraft/mc-mods/obscure-api/files/4132981), with this specific version being required for the mod Obscure Tooltips. The previous version doesn't crash. 
I have a log from the server, but client-side log shows no errors.
[Server Log](https://gist.github.com/WenXin20/9aa95e30411e0550d302ca31d5dc5263#file-server_latest-log-L25)

**Comment by AzureDoom** [comment]
Are you using anything with MixinExtras?

**Comment by WenXin20** [comment]
Oh sorry, just saw this. 
I'm not sure what mods use MixinExtras, if any I would suspect Obscure Api.

**Comment by AzureDoom** [comment]
This was found to be the fault of mods that are using the **beta** version of MixinExtra instead of the release version. New version is pushed using the beta.
