### ISSUE TITLE
Latest version crashes 1.19.2

### ISSUE THREAD

**Issue by Vinesauced** [AzureDoom/Erroring-Entity-Remover-ReForged#4]
the log from version 1.0.4 (1.19.2), crashed just at startup https://mclo.gs/tvZbjWb

**Comment by AzureDoom** [comment]
If you remove MixinExtras, does it work then?

**Comment by Vinesauced** [comment]
I can't exactly remove mixinextras, it was added by another mod and removing it probably breaks a ton of other mods.

**Comment by Vinesauced** [comment]
It gives the exact same error with no other mods in 1.19.2 https://mclo.gs/V0HeIfw

**Comment by AzureDoom** [comment]
> It gives the exact same error with no other mods in 1.19.2 https://mclo.gs/V0HeIfw

`--version 1.19.2 --gameDir /home/********/.local/share/PollyMC/instances/1.19.2/.minecraft --assetsDir /home/********/.local/share/PollyMC/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 45.0.49 --fml.mcVersion 1.19.4 --`

Shows you are trying to 1.19.4 on 1.19.2

Just tested in a clean 1.19.2 build and it's loading just fine for me. 
![2023-04-29_11 41 19](https://user-images.githubusercontent.com/7415711/235311211-0910b4ff-f9b0-424b-b1ba-936d589d1b17.png)

**Comment by AzureDoom** [comment]
This was found to be the fault of mods that are using the **beta** version of MixinExtra instead of the release version. New version is pushed using the beta.
