### ISSUE TITLE
Difference between this and default Forge option

### ISSUE THREAD

**Issue by SuperStormer** [AzureDoom/Erroring-Entity-Remover-ReForged#5]
What's the difference between this mod and Forge's default option(s)?

The relevant config lines (under `saves/world/serverconfig/forge-server.toml`):
```
[server]
	#Set this to true to remove any BlockEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
	removeErroringBlockEntities = false
	#Set this to true to remove any Entity (Note: Does not include BlockEntities) that throws an error in its tick method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
	removeErroringEntities = false
```

**Comment by AzureDoom** [comment]
During the time this was made, this open was removed, but the new options in the latest update stops the game from crashing better with broken block entities than the forge option as it just stops it ticking but doesn't delete so anything with an inventory you can still access.

**Comment by SuperStormer** [comment]
I see, thanks!
