### ISSUE TITLE
This mod isn't doing anything.

### ISSUE THREAD

**Issue by PercyJames** [AzureDoom/Erroring-Entity-Remover-ReForged#6]
I have this mod downloaded and it isn't removing a ticking entity.
[crash-2023-06-10_13.59.08-server.txt](https://github.com/AzureDoom/Erroring-Entity-Remover-ReForged/files/11713048/crash-2023-06-10_13.59.08-server.txt)

**Comment by AzureDoom** [comment]
This is an issue with the Curios mod and majrusz library due to bad nulling. That's always going to crash no matter what and is a type of crash outside this mods control to stop.
