### ISSUE TITLE
Does this mod remove entities that don't crash he game but spam the logs with errors?

### ISSUE THREAD

**Issue by Sshmoob** [AzureDoom/Erroring-Entity-Remover-ReForged#7]
On my server, the logs get spammed with the warning "skipping entity with id" every single tick, but it's not crashing the server, it's just spamming the logs so much I can't see something that might actually be important. 
I'm pretty sure this is due to me having chunkloaded beehives, but every time this happens, I have to find which beehive out of the 20 I have in my farm has the bugged bee and the kill the bee/throw the hive away and get a new one, which is just annoying.

I was wondering if this mod would automatically remove the erroring entity in this case even though it's not crashing the server and it's a vanilla error or not. If this isn't the case, could you add this functionality to the mod?

**Comment by AzureDoom** [comment]
That is outside the scope of this mods functionality. I suggest looking into Log Begone for removing the log spam
